# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rginv <- function(m) {
    .Call(`_autostsm_Rginv`, m)
}

gen_inv <- function(m) {
    .Call(`_autostsm_gen_inv`, m)
}

kalman_filter <- function(B0, P0, Dm, Am, Fm, Hm, Qm, Rm, yt, X, beta, smooth = FALSE) {
    .Call(`_autostsm_kalman_filter`, B0, P0, Dm, Am, Fm, Hm, Qm, Rm, yt, X, beta, smooth)
}

