# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rginv <- function(m) {
    .Call(`_autostsm_Rginv`, m)
}

gen_inv <- function(m) {
    .Call(`_autostsm_gen_inv`, m)
}

kalman_filter <- function(sp, yt, X, smooth = FALSE) {
    .Call(`_autostsm_kalman_filter`, sp, yt, X, smooth)
}

